spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: duxin521
    url: jdbc:mysql://192.168.228.133:3306/baizhi_work?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
mybatis-plus:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity